title: 雨后清晨的网络随笔
author: 雨后清晨
lang: zh-cmn-Hans
email: 513387@qq.com
description: > # this means to ignore newlines until "baseurl:"
  软件开发、工业控制、电子设备
# social links
twitter_username: cyjbox
github_username:  cyjbox

show_excerpts: true # set to false to remove excerpts on the homepage
excerpt_separator: <!--more-->
theme: jekyll-theme-minimal
